#ifndef CTP_ERRORNOS_H_
#define CTP_ERRORNOS_H_

#define CTP_ERRORNO_ALLOC    0
#define CTP_ERRORNO_SOCKET   1
#define CTP_ERRORNO_SOC_OPT  2
#define CTP_ERRORNO_BIND_SOC 3
#define CTP_ERRORNO_FORK     4

#endif
